### ISSUE TITLE
Error in getThreadList()

### ISSUE THREAD

**Issue by xcorat** [carpedm20/fbchat#10]
getThreadList() gives me an error in python 3.4. It was fixed by changing 

https://github.com/carpedm20/fbchat/blob/master/fbchat/client.py#L224

     t = Thread(thread)

to 

     t = Thread(**thread)

(I can fork and fix it if needed, unless you guys have already fixed it)

**Comment by PidgeyL** [comment]
I forked this, fixed this, and will create a pull request tonight, after taking a look at some other bugs

**Comment by carpedm20** [comment]
@PidgeyL Thx!

**Comment by carpedm20** [comment]
#12 Solved

**Comment by wannaphongcom** [comment]
how to use getThreadList() ?

**Comment by PidgeyL** [comment]
from the code: `def getThreadList(self, start, end=None):`, I'm assuming it's calculating back in time, where start is either 0 (the last message) or a number of messages to skip, and end is the x'th message

**Comment by wannaphongcom** [comment]
Error
code
```python
import fbchat
client = fbchat.Client("id", "pass")
print(client.getThreadList(0))
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\py34\lib\site-packages\fbchat\client.py", line 221, in getThreadList
    j = get_json(r.text)
  File "C:\py34\lib\site-packages\fbchat\utils.py", line 18, in get_json
    return json.loads(re.sub(r"for.*(.*;.*;.*).*;", '', text.encode('utf-8').dec
ode("unicode-escape"), 1))
  File "C:\py34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\py34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\py34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 2567 (char 2566)

**Comment by PidgeyL** [comment]
That's very odd. Doesn't seem like something I changed. Can you print the json from the getTrheadList?

**Comment by wannaphongcom** [comment]
No, I can't. :sob:

**Comment by PidgeyL** [comment]
Sure you can. when you download this project, add the following line to `fbchat/client.py`, on line 221:

`print(j)`

Then, run `sudo pip uninstall fbchat` (or pip3 if you're using python3) to uninstall the current fbchat
Then, run 'sudo python setup.py install' (or python3) to install your modified version
Then run the script again (or your code in the interpreter) to get the output of the json

I don't know if there is any personal data in the json file, I don't know it by heart. If you're using a dummy facebook account, it doesn't matter, but if you don't, perhaps have a look at the output, and replace any ouput that looks personal by fake output, but keep the same format (numbers vs letters, length, etc)

**Comment by wannaphongcom** [comment]
```python
import fbchat
client = fbchat.Client("id", "pass")
print(client.getThreadList(0))
```
```json
,"thread_fbid":null,"time":0000004752987},{"other_user_fbid":"000000395885","
thread_fbid":null,"time":00000098306},{"other_user_fbid":"00000088685","th
read_fbid":null,"time":000000001561}],"payload_source":"server_fetch_threadlist
_info"},"bootloadable":{},"ixData":{},"lid":"6224703000000533"}
```

**Comment by wannaphongcom** [comment]
Or, as Thai lang . Facebook used to encode non-utf-8.

**Comment by PidgeyL** [comment]
Sounds legit. I'll take a look when I have some time. When you look for "snippet" in the text, what does that look like? Text, Null, ...
?

**Comment by wannaphongcom** [comment]
from test. https://github.com/wannaphongcom/fbchat/commit/9d4d44372f0045175b6254b9894cfddeb8192701

>>> print(client.getThreadList(0))
Traceback (most recent call last):
  File "C:\py34\lib\site-packages\requests\packages\urllib3\connectionpool.py",
line 559, in urlopen
    body=body, headers=headers)
  File "C:\py34\lib\site-packages\requests\packages\urllib3\connectionpool.py",
line 345, in _make_request
    self._validate_conn(conn)
  File "C:\py34\lib\site-packages\requests\packages\urllib3\connectionpool.py",
line 782, in _validate_conn
    conn.connect()
  File "C:\py34\lib\site-packages\requests\packages\urllib3\connection.py", line
 250, in connect
    ssl_version=resolved_ssl_version)
  File "C:\py34\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line
285, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\py34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\py34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\py34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] การเชื่อมต่อที่มีอยู่ถูกบังคับให้ปิดโดยโฮ
สต์ระยะไกล

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\py34\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\py34\lib\site-packages\requests\packages\urllib3\connectionpool.py",
line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\py34\lib\site-packages\requests\packages\urllib3\util\retry.py", line
 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\py34\lib\site-packages\requests\packages\urllib3\packages\six.py", li
ne 309, in reraise
    raise value.with_traceback(tb)
  File "C:\py34\lib\site-packages\requests\packages\urllib3\connectionpool.py",
line 559, in urlopen
    body=body, headers=headers)
  File "C:\py34\lib\site-packages\requests\packages\urllib3\connectionpool.py",
line 345, in _make_request
    self._validate_conn(conn)
  File "C:\py34\lib\site-packages\requests\packages\urllib3\connectionpool.py",
line 782, in _validate_conn
    conn.connect()
  File "C:\py34\lib\site-packages\requests\packages\urllib3\connection.py", line
 250, in connect
    ssl_version=resolved_ssl_version)
  File "C:\py34\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line
285, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\py34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\py34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\py34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', Conn
ectionResetError(10054, 'การเชื่อมต่อที่มีอยู่ถูกบังคับให้ปิดโดยโฮสต์ระยะไกล', N
one, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\py34\lib\site-packages\fbchat\client.py", line 231, in getThreadList
    r = self._post("https://www.facebook.com/ajax/mercury/threadlist_info.php",
data)
  File "C:\py34\lib\site-packages\fbchat\client.py", line 79, in _post
    return self._session.post(url, headers=self._header, data=query, timeout=tim
eout)
  File "C:\py34\lib\site-packages\requests\sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\py34\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\py34\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\py34\lib\site-packages\requests\adapters.py", line 412, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetErro
r(10054, 'การเชื่อมต่อที่มีอยู่ถูกบังคับให้ปิดโดยโฮสต์ระยะไกล', None, 10054, Non
e))

**Comment by wannaphongcom** [comment]
feom test https://github.com/wannaphongcom/fbchat/commit/9d4d44372f0045175b6254b9894cfddeb8192701
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\py34\lib\site-packages\fbchat\client.py", line 235, in getThreadList
    j = get_json(r.text)
  File "C:\py34\lib\site-packages\fbchat\utils.py", line 18, in get_json
    return json.loads(re.sub(r"for.*(.*;.*;.*).*;", '', text.encode('utf-8').dec
ode("unicode-escape"), 1))
  File "C:\py34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\py34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\py34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 17182 (char 17181)
```

**Comment by PidgeyL** [comment]
yeah, I understand that, but I would need to know the format of the data, to see how to parse it properly :)

**Comment by wannaphongcom** [comment]
```json
{"fbid":10000660634020
8,"gender":2,"href":"https:\/\/www.facebook.com\/profile.php?id=","id":"fbid:friends","image_src":"https:\/\/f","big_image_src":"https:\/\/","name":"\u0e40\u0e0a\u0e19 ",
"short_name":"\u0e40","employee":false,"is_employee_away":false,"typ
e":"user","vanity":"","is_friend":true,"social_snippets":[],"is_messenger_user":
true}
```

**Comment by PidgeyL** [comment]
I think I see the issue. I wouldn't be surprised if regex couldn't handle unicode like that. Could you open a new issue with this information?

**Comment by wannaphongcom** [comment]
The result of getThreadList() Of you?

**Comment by PidgeyL** [comment]
Well this issue is closed (and a different issue), so could you open a new ticket which includes the info you put here, so we can work on it?
