### ISSUE TITLE
On python 2.7

### ISSUE THREAD

**Issue by posix4e** [carpedm20/fbchat#146]
Once I switched inspect over to funcsigs here's the error  I get

bash-4.3# gunicorn server:app
[2017-05-17 06:23:18 +0000] [10] [INFO] Starting gunicorn 19.7.1
[2017-05-17 06:23:18 +0000] [10] [INFO] Listening at: http://127.0.0.1:8000 (10)
[2017-05-17 06:23:18 +0000] [10] [INFO] Using worker: sync
[2017-05-17 06:23:18 +0000] [13] [INFO] Booting worker with pid: 13
[2017-05-17 06:23:19 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/server.py", line 14, in <module>
    facebook_client = fbchat.Client(facebook_username, facebook_pw)
  File "/usr/lib/python2.7/site-packages/fbchat/client.py", line 163, in __init__
    self.login(email, password, max_retries)
  File "/usr/lib/python2.7/site-packages/fbchat/client.py", line 358, in login
    self.onLoggingIn(email)
  File "/usr/lib/python2.7/site-packages/fbchat/event_hook.py", line 52, in __call__
    ", but was called with: (%s)" %self._signature)
ValueError: This EventHook must be called with these keyword arguments: (email=str), but was called with: ({'email': <type 'str'>})

**Comment by QuentinCG** [comment]
I got the same issue with Python 3.4 (my source code worked with install from previous version of fbchat): 

fbchat.Client.__init__(self, email, password, verbose)
  File "/usr/local/lib/python3.4/dist-packages/fbchat/client.py", line 163, in __init__
    self.login(email, password, max_retries)
  File "/usr/local/lib/python3.4/dist-packages/fbchat/client.py", line 358, in login
    self.onLoggingIn(email)
  File "/usr/local/lib/python3.4/dist-packages/fbchat/event_hook.py", line 52, in __call__
    ", but was called with: (%s)" %self._signature)
ValueError: This EventHook must be called with these keyword arguments: (email=str), but was called with: ({'email': <class 'str'>})

**Comment by madsmtm** [comment]
Sorry about the inconvenience, please downgrade to 0.9.0

**Comment by QuentinCG** [comment]
Ok, thanks for the answer :)

Is it a bug that will be fixed in future version of fbchat?

**Comment by Dainius14** [comment]
Yes. A new and much better version is in the works. Look at the `development` branch. You can try it out now, it's mostly done.

**Comment by QuentinCG** [comment]
`sudo pip3 install fbchat==0.9.0` fixed the issue ;)

Thanks !

**Comment by madsmtm** [comment]
I've properly updated the package on pypi, so that 0.10 is not downloaded. Sorry for the trouble :)
