### ISSUE TITLE
Logins stopped working last night at some point - 2017-06-05

### ISSUE THREAD

**Issue by amplogik** [carpedm20/fbchat#157]
all login actions now generate output similar to following ( have replaced password and login )

Traceback (most recent call last):
  File "./echobot.py", line 21, in <module>
    bot = EchoBot("example@example.com", "SamplePassword")
  File "./echobot.py", line 8, in __init__
    fbchat.Client.__init__(self,email, password, debug, user_agent)
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 124, in __init__
    self.login(email, password, max_retries)
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 336, in login
    if not self._login():
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 243, in _login
    self._post_login()
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 200, in _post_login
    self.payloadDefault['__rev'] = int(r.text.split('"revision":',1)[1].split(",",1)[0])
IndexError: list index out of range

Have tried multiple accounts, and saved sessions also generate the same issue.

Anyone else getting this?

**Comment by newtonseple** [comment]
I got the exact same error

**Comment by madsmtm** [comment]
This was fixed recently in v. 9.0.2, Facebook changed their code ;)
