### ISSUE TITLE
error after logged in for days

### ISSUE THREAD

**Issue by JarbasAI** [carpedm20/fbchat#187]
i'm now having this error i didn't have before, happens when online for a while, its started after a pip upgrade of fbchat, internet connection is stable and running well

seems to happen when i check if still logged in after being online 1+ days

```
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/test/mycroft-server/server_skills/skill_facebook/__init__.py", line 401, in listen
    if not self.isLoggedIn():
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 281, in isLoggedIn
    r = self._cleanGet(ReqUrl.LOGIN)
  File "/home/test/mycroft-server/server_skills/skill_facebook/__init__.py", line 416, in _cleanGet
    return self._session.get(url, headers=self._header, params=query, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='m.facebook.com', port=443): Read timed out. (read timeout=90)

```

**Comment by Bankde** [comment]
It's possible this happens after https://github.com/carpedm20/fbchat/pull/178
I know some server will decline to reply if it detects some invalid parameters or out-of-state. Im not sure exactly how facebook handle session. I will look more into this one.

I can run facebook for weeks without having problem, however I never check isLoggedIn function.
@madsmtm Have you got any error from running for several days ?

**Comment by madsmtm** [comment]
Though this never happened, I did get a 502 response on `_pullMessage`, though I have yet to investigate further

**Comment by madsmtm** [comment]
I just ran into this while executing `tests.py`, though while calling `changeThreadEmoji`, and not `isLoggedIn`:

```
Traceback (most recent call last):
  File "tests.py", line 171, in test_changeThreadEmoji
    client.changeThreadEmoji('😀', user_id)
  File "/Users/madsmarquart/Desktop/Code/fbchat/fbchat/client.py", line 1118, in changeThreadEmoji
    j = checkRequest(self._post(ReqUrl.THREAD_EMOJI, data))
  File "/Users/madsmarquart/Desktop/Code/fbchat/fbchat/client.py", line 93, in _post
    return self._session.post(url, headers=self._header, data=payload, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/adapters.py", line 516, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.facebook.com', port=443): Read timed out. (read timeout=30)
```

I would guess that Facebook just sometimes drops the connection. Maybe after sending too many requests too quickly?

**Comment by madsmtm** [comment]
Update. Got same result as @JarbasAI, but only after being logged in for max. 5 hours:
```
Traceback (most recent call last):
  File "/var/facebook/facebook.py", line 62, in <module>
    client.listen()
  File "/var/facebook/state_client.py", line 16, in listen
    super(StateClient, self).listen(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 1465, in listen
    while self.listening and self.doOneListen(markAlive):
  File "/var/facebook/custom_client.py", line 397, in doOneListen
    content = self._pullMessage(self.sticky, self.pool)
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 1249, in _pullMessage
    j = checkRequest(self._get(ReqUrl.STICKY, data))
  File "/usr/local/lib/python3.5/dist-packages/fbchat/utils.py", line 157, in checkRequest
    raise Exception('Error when sending request: Got {} response: {}, with request {} : {}'.format(r.status_code, get_decoded_r(r), r.request.url, r.request.body))
Exception: Error when sending request: Got 502 response
```

Response content:
```
<!DOCTYPE html>
<html lang="en" id="facebook">
  <head>
    <title>Facebook | Error</title>
    <meta charset="utf-8">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="cache-control" content="no-store">
    <meta http-equiv="cache-control" content="max-age=0">
    <meta http-equiv="expires" content="-1">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="robots" content="noindex,nofollow">
    <style>
      html, body {
        color: #141823;
        background-color: #e9eaed;
        font-family: Helvetica, Lucida Grande, Arial,
                     Tahoma, Verdana, sans-serif;
        margin: 0;
        padding: 0;
        text-align: center;
      }

      #header {
        height: 30px;
        padding-bottom: 10px;
        padding-top: 10px;
        text-align: center;
      }

      #icon {
        width: 30px;
      }

      h1 {
        font-size: 18px;
      }

      p {
        font-size: 13px;
      }

      #footer {
        border-top: 1px solid #ddd;
        color: #9197a3;
        font-size: 12px;
        padding: 5px 8px 6px 0;
      }
    </style>
  </head>
  <body>
    <div id="header">
      <a href="//www.facebook.com/">
        <img id="icon" src="//static.xx.fbcdn.net/images/logos/facebook_2x.png" />
      </a>
    </div>
    <div id="core">
      <h1 id="sorry">Sorry, something went wrong.</h1>
      <p id="promise">
        We're working on it and we'll get it fixed as soon as we can.
      </p>
      <p id="back-link">
        <a id="back" href="//www.facebook.com/">Go Back</a>
      </p>
      <div id="footer">
        Facebook
        <span id="copyright">
          &copy; 2017
        </span>
        <span id="help-link">
          &#183;
          <a id="help" href="//www.facebook.com/help/">Help Center</a>
        </span>
      </div>
    </div>
    <script>
      document.getElementById('back').onclick = function() {
        if (history.length > 1) {
          history.back();
          return false;
        }
      };

      // Adjust the display based on the window size
      if (window.innerHeight < 80 || window.innerWidth < 80) {
        // Blank if window is too small
        document.body.style.display = 'none';
      };
      if (window.innerWidth < 200 || window.innerHeight < 150) {
        document.getElementById('back-link').style.display = 'none';
        document.getElementById('help-link').style.display = 'none';
      };
      if (window.innerWidth < 200) {
        document.getElementById('sorry').style.fontSize = '16px';
      };
      if (window.innerWidth < 150) {
        document.getElementById('promise').style.display = 'none';
      };
      if (window.innerHeight < 150) {
        document.getElementById('sorry').style.margin = '4px 0 0 0';
        document.getElementById('sorry').style.fontSize = '14px';
        document.getElementById('promise').style.display = 'none';
      };
    </script>
  </body>
</html>
```

After that, I could still fetch messages in subsequent pull requests, but whenever trying to do anything, I got a `Log in to continue` error (I think, though this could be caused by something else)

**Comment by Bankde** [comment]
I believe pulling message also get fb_dtsg (which is semi-session)
Previously, I only updated fb_dtsg when receiving message. I didn't check on pull message.

You sure old version is still working fine ? If my above assumption is correct, it should happen on all versions of fbchat.

**Comment by madsmtm** [comment]
I just went ahead and edited `utils.py`, line 157, in `checkRequest` to:
```
raise Exception('Error when sending request: Got {} response: {}, with request {} : {}'.format(r.status_code, get_decoded_r(r), r.request.url, r.request.body))
```

Though you should be able to see all requests/responses with what you're doing?

**Comment by Bankde** [comment]
I'm still missing requests/response from client.isLoggedIn() but that could be later, I will focus on client.listen() first. Thanks.

**Comment by JarbasAI** [comment]
any news on this? just got my bot online again, let me know if i can help test something

**Comment by Bankde** [comment]
Hi. Sry I forgot to update.

I can't reach the final conclusion yet; however these information might help.
1. I never have problem from running 12-16 hours of persistent connection. (Try 4-5 times)
2. I can use the same session across the weeks (2 weeks) without a sign of any problem.
3. To be short, I can't reproduce it XD
For my own reason, I never leave a connection open for more than 16 hours though.

It seems like a facebook-side issue (either server or load balancer or anything) that cause connection to be cut after a while.
If it still happens, I guess I will have to find another spare computer to test a persistent connection.

**Comment by Bankde** [comment]
Is this issue still happening ?
I have run my own application (with listening too) for 2 months and it's still working fine.
According to my log, there are one time that sendMessage failed and got 500 response. Since I catch, print error and let it pass, my application can continue running fine after that using very same session.

Overall, I would say it's facebook server issue. Any other observations ?

**Comment by tdtgit** [comment]
If it's Facebook server issues, can we bypass or just retry for few times? Got this error after running about 5 hours running. I tried this script for a year but they never run for a day, just a few hours and die in some how.

```
Traceback (most recent call last):
  File "datuan.py", line 57, in <module>
    client.listen()
  File "build/bdist.linux-x86_64/egg/fbchat/client.py", line 1466, in listen
  File "build/bdist.linux-x86_64/egg/fbchat/client.py", line 1436, in doOneListen
  File "build/bdist.linux-x86_64/egg/fbchat/client.py", line 1222, in _ping
  File "build/bdist.linux-x86_64/egg/fbchat/client.py", line 96, in _get
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='0-edge-chat.facebook.com', port=443): Max retries exceeded with url: /active_ping?viewer_uid=100021792824930&__a=1&__user=100021792824930&seq=395&cap=0&state=active&clientid=7a13e7d&partition=-2&ttstamp=6581709875116108789888121115586581728474679012282119100722&__rev=3732925&fb_dtsg=AQFbKtlNbXys%3AAQHTJCZzRwdH&__req=1m3&uid=100021792824930&sticky_pool=atn1c08_chat-proxy&channel=p_100021792824930&sticky_token=62 (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)
```

**Comment by tdtgit** [comment]
@Bankde I'm tried running fbchat in some VPS(s): Vultr, Linode, etc with best network and low latency (I think) and this bot still die after 1 day or less. Me and my friend think the problem is inactivity in group chat so they don't have any to listen. Anyway, here new error lead to die today:

```
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/fbchat/client.py", line 1438, in doOneListen
    content = self._pullMessage(self.sticky, self.pool)
  File "build/bdist.linux-x86_64/egg/fbchat/client.py", line 1250, in _pullMessage
    j = checkRequest(self._get(ReqUrl.STICKY, data))
  File "build/bdist.linux-x86_64/egg/fbchat/utils.py", line 157, in checkRequest
    raise Exception('Error when sending request: Got {} response'.format(r.status_code))
Exception: Error when sending request: Got 502 response
```
