### ISSUE TITLE
Error logging in.

### ISSUE THREAD

**Issue by lollichop** [carpedm20/fbchat#223]
```
Traceback (most recent call last):
  File "path/listen.py", line 17, in <module>
    bot = Pytrana(your_email_here, your_password_here)
  File "path/listen.py", line 6, in __init__
    fbchat.Client.__init__(self, email, password, debug, user_agent)
  File "path\fbchat\client.py", line 73, in __init__
    self.login(email, password, max_tries)
  File "path\fbchat\client.py", line 374, in login
    if max_tries < 1:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

The value of variable `max_tries` seems to be initialized as `None` inside the function `login(self, email, password, max_tries=5)` , line #360, `client.py`.

**Comment by lollichop** [comment]
This issue was produced when an older version of the module was used. Works perfectly on the latest build.
