### ISSUE TITLE
Getting error on running interact.py from examples.

### ISSUE THREAD

**Issue by igauravsehrawat** [carpedm20/fbchat#227]
```
Traceback (most recent call last):
  File "interract.py", line 13, in <module>
    client.send(Message(text='Test message'), thread_id=thread_id, thread_type=thread_type)
  File "/usr/local/lib/python3.6/site-packages/fbchat/client.py", line 955, in send
    return self._doSendRequest(data)
  File "/usr/local/lib/python3.6/site-packages/fbchat/client.py", line 923, in _doSendRequest
    j = self._post(self.req_url.SEND, data, fix_request=True, as_json=True)
  File "/usr/local/lib/python3.6/site-packages/fbchat/client.py", line 128, in _post
    raise e
  File "/usr/local/lib/python3.6/site-packages/fbchat/client.py", line 124, in _post
    return check_request(r, as_json=as_json)
  File "/usr/local/lib/python3.6/site-packages/fbchat/utils.py", line 206, in check_request
    check_json(j)
  File "/usr/local/lib/python3.6/site-packages/fbchat/utils.py", line 185, in check_json
    raise FBchatFacebookError('Error #{} when sending request: {}'.format(j['error'], j['errorDescription']), fb_error_code=j['error'], fb_error_message=j['errorDescription'])
fbchat.models.FBchatFacebookError: Error #1545012 when sending request: There was a temporary error, please try again.
```
I am trying to post to this group: https://www.facebook.com/groups/491794801205862/?fref=nf
Below is the relevant code after successfully authenticating.
```
thread_id = '491794801205862'
thread_type = ThreadType.GROUP

client.send(Message(text='Test message'), thread_id=thread_id, thread_type=thread_type)
```
I am able to post if I login using browser though.

Can anyone give a hint on what is wrong with the code? 

Thanks

**Comment by madsmtm** [comment]
The thing you are posting to is a group, not a group *chat*. `fbchat` only has functionality to work on group chats. Go to [Messenger](https://www.facebook.com/messages) to get a feel for the things that the module was built for.
And no, we won't at some point add this functionality ;)

**Comment by igauravsehrawat** [comment]
Right, my bad. I should be using [Graph API](https://developers.facebook.com/docs/graph-api/overview) for that.

Thanks
