### ISSUE TITLE
self.AddUsersToGroup Error

### ISSUE THREAD

**Issue by LThistle** [carpedm20/fbchat#243]
I'm trying to write a program where you can easily add someone to a chat. I'm able to get the UID successfully, however when I execute self.AddUsersToGroup([the person's uid], thread_id=thread_id) I get "Error #1545052 when sending request: The user could not be added to the conversation. Please try again later."

>>> c.addUsersToGroup(100014307074396, cid)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/csl.tjhsst.edu/students/2021/2021lthistle/fbchat-workspace/lib/python3.5/site-packages/fbchat/client.py", line 1067, in addUsersToGroup
    return self._doSendRequest(data)
  File "/afs/csl.tjhsst.edu/students/2021/2021lthistle/fbchat-workspace/lib/python3.5/site-packages/fbchat/client.py", line 923, in _doSendRequest
    j = self._post(self.req_url.SEND, data, fix_request=True, as_json=True)
  File "/afs/csl.tjhsst.edu/students/2021/2021lthistle/fbchat-workspace/lib/python3.5/site-packages/fbchat/client.py", line 128, in _post
    raise e
  File "/afs/csl.tjhsst.edu/students/2021/2021lthistle/fbchat-workspace/lib/python3.5/site-packages/fbchat/client.py", line 124, in _post
    return check_request(r, as_json=as_json)
  File "/afs/csl.tjhsst.edu/students/2021/2021lthistle/fbchat-workspace/lib/python3.5/site-packages/fbchat/utils.py", line 205, in check_request
    check_json(j)
  File "/afs/csl.tjhsst.edu/students/2021/2021lthistle/fbchat-workspace/lib/python3.5/site-packages/fbchat/utils.py", line 184, in check_json
    raise FBchatFacebookError('Error #{} when sending request: {}'.format(j['error'], j['errorDescription']), fb_error_code=j['error'], fb_error_message=j['errorDescription'])
fbchat.models.FBchatFacebookError: Error #1545052 when sending request: The user could not be added to the conversation. Please try again later.

**Comment by madsmtm** [comment]
I'm pretty sure you have to be friends on Facebook with the person you are trying to add to the group. Perhaps that's the issue? Otherwise, perhaps you could show some more code?
