### ISSUE TITLE
client.send() is not working

### ISSUE THREAD

**Issue by abirlal** [carpedm20/fbchat#303]
After login succesfully i am executing this statement
client.send(Message(text='Hi me'), thread_id=client.uid, thread_type=ThreadType.USER)
below is the error
```
Traceback (most recent call last):
  File "fbTest.py", line 19, in <module>
    msg_id = client.send(Message(text='Hi me'), thread_id=client.uid, thread_type=ThreadType.USER)
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 951, in send    return self._doSendRequest(data)
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 919, in _doSendRequest
    j = self._post(self.req_url.SEND, data, fix_request=True, as_json=True)
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 127, in _post return check_request(r, as_json=as_json)
  File "C:\Python27\lib\site-packages\fbchat\utils.py", line 209, in check_request
    content = strip_to_json(content)
  File "C:\Python27\lib\site-packages\fbchat\utils.py", line 146, in strip_to_json
    raise FBchatException('No JSON object found: {}, {}'.format(repr(text), text.index('{')))
ValueError: substring not found
```

**Comment by madsmtm** [comment]
Well, the error message is really cryptic, because the error that `text.index('{')` throws is caught, and then thrown again in the next line
```py
def strip_to_json(text):
    try:
        return text[text.index('{'):]
    except ValueError:
        raise FBchatException('No JSON object found: {}, {}'.format(repr(text), text.index('{')))
```
But why it isn't able to find any JSON, I have no clue, perhaps Facebook gave you an error page showing HTML? Can you reproduce the issue, or was it a one-time deal?

**Comment by abirlal** [comment]
@madsumtm I am getting this error always. Login work fine and I am getting my ID also I can able to fetch all users. but when ever i am doing this function call it is showing this.

**Comment by madsmtm** [comment]
Hmm, can you try modifying the line in `strip_json` to this:
```
def strip_to_json(text):
    try:
        return text[text.index('{'):]
    except ValueError:
        raise FBchatException('No JSON object found: {}'.format(repr(text)))
```
So we can see what's going on?

**Comment by abirlal** [comment]
@madsmtm can u please let me know where to do the modification explicitly. Thanks in advance.

**Comment by madsmtm** [comment]
Sorry, yeah, start by finding the file where `fbchat.utils` is stored:
```sh
$ python -m pip show fbchat
...
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
...
```
In this case you'd edit `/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fbchat/utils.py`.
You'd modify line 147 like this:
```
     try:
         return text[text.index('{'):]
     except ValueError:
-        raise FBchatException('No JSON object found: {}, {}'.format(repr(text), text.index('{')))
+        raise FBchatException('No JSON object found: {!r}'.format(text))
 
 def get_decoded_r(r):
     return get_decoded(r._content)
```
I would've included this in the `1.3.9` update, but I forgot ;)

**Comment by abirlal** [comment]
It is working in 3.6.x version of python.

**Comment by madsmtm** [comment]
Glad you got it working, but this library should work in all supported python versions, so I'll reopen this

**Comment by madsmtm** [comment]
The logging is now proper since release `v1.4.0`, if you ever get around to it, I'd like you to try again, and provide me with the log output 😊
