### ISSUE TITLE
Error with getThreadMessages

### ISSUE THREAD

**Issue by codingJWilliams** [carpedm20/fbchat#350]
## Description of the problem
I get a key error when trying to use client.getThreadMessages

## Code to reproduce
```py
from fbchat import Client
from fbchat.models import *
import time
client = Client('redacted', 'redacted')

before = time.time()

hasMoreMessages = True
while hasMoreMessages:
    current = client.fetchThreadMessages(thread_id='1813947025313467', limit=20, before=before)
    print(len(current))
    print(current[0])
    break

```

## Traceback
```
Traceback (most recent call last):
  File "C:/Users/Jay Williams/Desktop/scrapeee.py", line 10, in <module>
    current = client.fetchThreadMessages(thread_id='1813947025313467', limit=20, before=before)
  File "C:\Users\Jay Williams\AppData\Local\Programs\Python\Python37\lib\site-packages\fbchat\client.py", line 854, in fetchThreadMessages
    'before': before
  File "C:\Users\Jay Williams\AppData\Local\Programs\Python\Python37\lib\site-packages\fbchat\client.py", line 189, in graphql_request
    return self.graphql_requests(query)[0]
  File "C:\Users\Jay Williams\AppData\Local\Programs\Python\Python37\lib\site-packages\fbchat\client.py", line 180, in graphql_requests
    'queries': graphql_queries_to_json(*queries)
  File "C:\Users\Jay Williams\AppData\Local\Programs\Python\Python37\lib\site-packages\fbchat\client.py", line 141, in _graphql
    return graphql_response_to_json(content)
  File "C:\Users\Jay Williams\AppData\Local\Programs\Python\Python37\lib\site-packages\fbchat\graphql.py", line 361, in graphql_response_to_json
    rtn[int(key[1:])] = value['data']
KeyError: 'data'
```

## Environment information
- Python version 3.7
- `fbchat` version 1.4.1

**Comment by ekohilas** [comment]
Hi @codingJWilliams,
Thanks for the report!
Unfortunately it's quite difficult to tell why the error would occur without some context of the message.
Especially when the error stopped the following log report.

Would you be able to provide an example of the message you were trying to pull?

Otherwise, you could probably change that line of code to `rtn[int(key[1:])] = value.get('data')` if you want to temporarily ignore the error.

It's likely someone else would know more than me though.

**Comment by lordchalky** [comment]
Hi @codingJWilliams, 

It appears as though you're passing the timestamp as a floating point number rather than as an integer as `fetchThreadMessages` requires. `time.time()` returns the seconds since epoch as a floating point number.

When you have a mo' cast `before` as an integer and then let us know what happens.

**Comment by codingJWilliams** [comment]
@ekohilas oops I didn’t see your message, sorry
@lordchalky Yeah I figured that out by myself! Also I think I had to times it by 1000, I can’t remember. Anyway yeah was user error! Thanks

**Comment by madsmtm** [comment]
As a future not to myself, this could've been avoided by #278
