### ISSUE TITLE
Installation error when running "pip install fbchat"

### ISSUE THREAD

**Issue by singhayush** [carpedm20/fbchat#362]
## fbchat fails to install

# Example code
```
pip install fbchat
```

## Traceback
```
Collecting fbchat
Collecting enum34; python_version < "3.4" (from fbchat)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Installing collected packages: enum34, fbchat
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\_internal\cli\base_command.py", line 143, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\_internal\commands\install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "c:\python27\lib\site-packages\pip\_internal\req\__init__.py", line 49, in install_given_reqs
    **kwargs
  File "c:\python27\lib\site-packages\pip\_internal\req\req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "c:\python27\lib\site-packages\pip\_internal\req\req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "c:\python27\lib\site-packages\pip\_internal\wheel.py", line 326, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: fbchat .dist-info directory not found
```

## Environment information
- Python version 2.7
- `fbchat` version
- If relevant, output from `$ python -m pip list`

I have already tried removing the enum34 directories and reinstalling but the error persists.

**Comment by madsmtm** [comment]
Can you give us your `pip` and `setuptools` version?
```sh
pip show pip setuptools
```
And maybe try updating those?
```
pip install -U pip setuptools
```

**Comment by singhayush** [comment]
pip version: 18.1
I updated setuptools to 40.6.2 but the error is still there.

**Comment by singhayush** [comment]
any updates for this error?

**Comment by singhayush** [comment]
Is there any other info which you require from my side? Kindly respond atleast whether this can be fixed or no so that I can move on with my work.

**Comment by madsmtm** [comment]
I'm sorry, I don't know how to fix this. `fbchat`'s `setup.py` uses `setup.cfg`, which is a newer `setuptools` feature. When installing via the `setup.py` file, the project was registered as `UNKNOWN`, which tells me that the `setup.cfg` file was never parsed, and that the `setuptools` version is wrong?

My best bet would be that you're not using the same python version everywhere, to make sure you can use:
```sh
python -m pip install -U pip setuptools
python -m pip install fbchat
# or
python -m pip install -U pip setuptools
python -m setup.py install
```
Another thing you could try is creating a [virtual environment](https://docs.python.org/library/venv.html), (for python 2.7, of course), and then repeat the steps above?

**Comment by madsmtm** [comment]
I've noticed that I forgot to upload the Python 2 wheels in the latest version, can you try installing version `1.4.0`, and giving me the output?
```sh
python -m pip install fbchat==1.4.0
```

**Comment by mohitsharma001** [comment]
I have the same error tell me how to solve this error

**Comment by mohitsharma001** [comment]
This is all my same error...
ERROR: Exception:
Traceback (most recent call last):
  File "c:\windows\system32\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "c:\windows\system32\venv\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "c:\windows\system32\venv\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\windows\system32\venv\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\windows\system32\venv\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "c:\windows\system32\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "c:\windows\system32\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "c:\windows\system32\venv\lib\site-packages\pip\_internal\distributions\source\legacy.py", line 37, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "c:\windows\system32\venv\lib\site-packages\pip\_internal\distributions\source\legacy.py", line 90, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "c:\windows\system32\venv\lib\site-packages\pip\_vendor\pep517\wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "c:\windows\system32\venv\lib\site-packages\pip\_vendor\pep517\wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "c:\windows\system32\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "C:\Users\Mohit Sharma\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools.build_meta'
