### ISSUE TITLE
FBchatException: Could not fetch thread 2355367: {u'message_thread': None}

### ISSUE THREAD

**Issue by mattyicer** [carpedm20/fbchat#381]
## Description of the problem
FBchatException: Could not fetch thread 2355367: {u'message_thread': None} - It has something to do with the line `thread_id=client.uid`

## Code to reproduce
```py
# Example code
from fbchat import  Client, log
from fbchat.models import *
import fileinput

class punkjj(Client):

    def onMessage(self, author_id=None, message_object=None, thread_id=None, thread_type=ThreadType.USER, **kwargs):
        toggle = client.fetchThreadMessages(thread_id=client.uid, limit=1) # client.uid means its our own acc
        for message in toggle:
            pText=message.text.lower()
        if("online" in pText):
            self.markAsRead(author_id)
        log.info("Message {} from {} in {}".format(message_object, thread_id, thread_type))  
        msgText = message_object.text.lower()
        if(msgText=="hi" or msgText=="hii" or msgText=="hiii" or msgText=="yo" or msgText=="hi there" or msgText=="hey" or msgText=="heyy"):
            reply = "Hello :D"
        elif(msgText=="hello" or msgText=="hellow" or msgText=="heloo" or msgText=="hlo" or msgText=="hellow"):
            reply = "Hi :)"
        elif(msgText=="hy" or msgText=="hyy"):
            reply = "Hello :D"
        elif(msgText=="whatsup" or msgText=="wassup" or msgText=="what's up" or msgText=="wtsup" or msgText=="watsup" or msgText=="whats up" or "how are you" in msgText or "hw r u" in msgText):
            reply = "Awesome. What about you? :D"
        elif(msgText=="test" or msgText=="debug" or msgText=="aboutme" or msgText=="about" or msgText=="bot"):
            reply = "Hi, I'm a bot written in Python. Created by Pankaj Sheoran"
        elif("birthday" in msgText or "bday" in msgText or "hbd" in msgText):
            reply = "Thank you! :D"
        elif("what you doing" in msgText):
            reply = "Idling, I'm a bot afterall. I work for my creator, Pankaj Sheoran (www.punkjj.cf)"
        elif("bye" in msgText or msgText=="byye" or msgText=="byee"):
            reply = "Ok bye! :D"
        else:
            reply = "Thank you for contacting me. I'm currently not online, I was replying using a Python Script. I will reach out to you shortly."
        def sendMsgg():
            if (author_id!=self.uid):
                self.send(Message(text=reply), thread_id=thread_id, thread_type=thread_type)
            self.markAsDelivered(author_id, thread_id)     
        if ("online" in pText):
            sendMsgg()

client = punkjj("EMAIL", "PASSWORD")

client.listen()
```

## Traceback
```
Traceback (most recent call last):
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/fbchat/client.py", line 2278, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "test.py", line 10, in onMessage
    toggle = client.fetchThreadMessages(thread_id=client.uid, limit=1) # client.uid means its our own acc
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/fbchat/client.py", line 845, in fetchThreadMessages
    raise FBchatException('Could not fetch thread {}: {}'.format(thread_id, j))
FBchatException: Could not fetch thread 2355367: {u'message_thread': None}

```

## Environment information
- Python  2.7
- `fbchat` (1.4.2)
- If relevant, output from `$ python -m pip list`

If you have done any research, include that.
Make sure to redact all personal information.

I've search google, but I'm fairly new this API and there wasn't any examples of "auto-reply" except for one script I found on the web called [FB-AutoReply](https://github.com/punkjj/FB-AutoReply/blob/master/main.py). That's all I know. Please help. I believe it has something to do with the "client.uid" in which it's adding my Profile ID, and I don't understand why it needs that. Has this script worked for anyone else?

**Comment by madsmtm** [comment]
The script you're using, `FB-AutoReply`, is developed separately from this project, and looks like it's mostly just a personal script that the author published, so it's not really in my power to support that. I see you've created punkjj/FB-AutoReply#1, so you can hope to get some answers there instead.

But I can tell you a few things about the line that causes the exception:
```py
toggle = client.fetchThreadMessages(thread_id=client.uid, limit=1)
```
This fetches the latest message sent from you, to yourself, so you won't need this in _your_ script. The author probably included it as some way to control their bot.
The reason it's failing though, is probably because you haven't sent any messages to yourself, and therefore the client can't fetch them! (though the error message is misleading).

But anyhow, you should have a look at the [`EchoBot`](https://fbchat.readthedocs.io/en/master/examples.html#echobot) example instead. That describes how you'd recieve messages, and optionally react to them.

`EchoBot` recieves a `message_object` while listening, and just to get you started, then it has the attributes of [`Message`](https://fbchat.readthedocs.io/en/master/api.html#fbchat.models.Message). If you simply want to do text manipulation on that, you can use `message_object.message`, which contains the body of the message.

**Comment by mattyicer** [comment]
Thanks for the reply. Yes, I've also posted this issue onto the FB-AutoReply Github page. I looked at the EchoBot example and it works, but I just want a simple script in which, when a user replies with a certain word like "**Tink**", then the script will send a message to that user. If "**Tink**" was not mention, then don't send any message at all. Would you be able to help create that with me? 

Now, Regarding the FB-AutoReply, Which by the way, it very close to what I want, however I keep getting that error. Now, why would "_he_" want to send a message to himself? with this line of code:

`toggle = client.fetchThreadMessages(thread_id=client.uid, limit=1)`

> The reason it's failing though, is probably because you haven't sent any messages to yourself, and therefore the client can't fetch them! (though the error message is misleading).

1. What do you mean "misleading"? 
2. Are you saying that the script only works if I send a message to myself?

I apologize in advance due to my lack of knowledge of FBchat. :)

**Comment by mattyicer** [comment]
So, I took your code and applied it to the script...But I'm getting a new error. I feel that we're so close hahaha. 

Traceback:

```
  File "tes.py", line 19, in onMessage
    self.sendMessage(Message(text=reply), thread_id=thread_id, thread_type=thread_type)
NameError: global name 'Message' is not defined
Inbox event: 1, 1, 1
```

**Comment by madsmtm** [comment]
Right, you need to import `Message` from `fbchat.models` :wink:

**Comment by mattyicer** [comment]
So I added the Message to the import line and it works. Just ONE more question. I notice when my friend receives the auto message, he gets the following info...

`<Message (None): 'success', mentions=[] emoji_size=None attachments=[]>`

Hahah, why is it doing that?

**Comment by madsmtm** [comment]
Oops, I think I misguided you, you should use `Client.send`, not `Client.sendMessage` as I described. I've updated my comment to fix this 😊

**Comment by mattyicer** [comment]
wait..so I do this:

```
if author_id != self.uid:
            Client.send(Message(text=reply), thread_id=thread_id, thread_type=thread_type)
```
