### ISSUE TITLE
NameError name 'data' is not defined

### ISSUE THREAD

**Issue by wannaphongcom** [carpedm20/fbchat#4]
My facebook login id and password is true. but
```python
>>> import fbchat
>>> client = fbchat.Client("ID", "PASSWORD")
Logging in...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\py34\lib\site-packages\fbchat-0.0.2-py3.4.egg\fbchat\client.py", line
 68, in __init__
NameError: name 'data' is not defined
```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AM
D64)] on win32

Thank you.

**Comment by carpedm20** [comment]
I think I updated wrong codes to pypi. I'll fix this asap.

**Comment by wannaphongcom** [comment]
It's bug.
I using
```python
>>> import fbchat
>>> client = fbchat.Client("ID", "PASSWORD")
Logging in...
>>> client.getUsers("name")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\facebook\fbchat-master\fbchat-master\fbchat\client.py", line 151, in
getUsers
    self.j = j = get_json(r.text)
  File "F:\facebook\fbchat-master\fbchat-master\fbchat\utils.py", line 18, in ge
t_json
    return json.loads(re.sub(r"for.*(;;).*;", '', text.encode('utf-8'), 1))
  File "C:\py34\lib\re.py", line 179, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by aviaryan** [comment]
This is still not fixed. The bug occured in the last commit https://github.com/carpedm20/fbchat/commit/9c1042f1931ba89fc50ce5cf5afd4323b1e1eb36
See https://github.com/carpedm20/fbchat/commit/9c1042f1931ba89fc50ce5cf5afd4323b1e1eb36#diff-a78c2e0b87b43778c8ca25b8f55918faR68

**Comment by wannaphongcom** [comment]
Fix https://github.com/carpedm20/fbchat/pull/7
