### ISSUE TITLE
Facebook friendship anniversary video breaks fetchTreadMessages

### ISSUE THREAD

**Issue by femt0** [carpedm20/fbchat#418]
## Description of the problem
fetchThreadMessage fails to fetch [Facebook friendship anniversary video](https://www.youtube.com/watch?v=b3PBN3zC4M0&t=1s) shared to messenger.

## Code to reproduce
```py
# Example code
from fbchat import Client
client = Client("[REDACTED_USERNAME]", "a_password_with_%")
```

Attachment causing the issue (in french) :
```js
'story_attachment': {
	'description': {
		'text': '... et ... sont ami(e)s sur Facebook depuis 5 ans. Regardez la vidéo qui fête cette amitié.'
	},
	'media': {
		'animated_image': None,
		'image': {
			'uri': 'https://scontent.fcdg2-1.fna.fbcdn.net/v/...',
			'height': 426,
			'width': 426
		},
		'playable_duration_in_ms': 0,
		'is_playable': False,
		'playable_url': None
	},
	'source': None,
	'style_list': ['fallback', 'fallback'],
	'title_with_entities': {
		'text': 'Un amiversaire à fêter\xa0!'
	},
	'properties': [],
	'url': 'https://www.facebook.com/onthisday/message/?cid=XXX&source=message',
	'deduplication_key': '...',
	'action_links': [],
	'messaging_attribution': None,
	'target': {
		'__typename': 'ExternalUrl'
	},
	'subattachments': []
}
```

## Traceback
```
Traceback (most recent call last):
...
  File "/.../ENV/lib/python3.7/site-packages/fbchat/client.py", line 1105, in fetchThreadMessages
    for message in j["message_thread"]["messages"]["nodes"]
  File "/.../ENV/lib/python3.7/site-packages/fbchat/client.py", line 1105, in <listcomp>
    for message in j["message_thread"]["messages"]["nodes"]
  File "/.../ENV/lib/python3.7/site-packages/fbchat/graphql.py", line 399, in graphql_to_message
    attachment = graphql_to_extensible_attachment(message["extensible_attachment"])
  File "/.../ENV/lib/python3.7/site-packages/fbchat/graphql.py", line 202, in graphql_to_extensible_attachment
    source=story["source"].get("text"),
AttributeError: 'NoneType' object has no attribute 'get'
```

## Environment information
Python version 3.7
fbchat version 1.6.4

**Comment by madsmtm** [comment]
Thanks for the report, I'll fix it in an upcoming release!
