### ISSUE TITLE
Facebook new colors break non standart color

### ISSUE THREAD

**Issue by TurtleForGaming** [carpedm20/fbchat#425]
## Description of the problem
Putting a thread color to a gradient breaks all the methods from fbchat

## Way to reproduce
Just put a conversation in gradient mode

## Traceback
```
Exception in parsing of {u'queue': 100012776436889L, u'ofd_ts': 1556220634599L, u'iseq': 315433, u'type': u'delta', u'delta': {u'body': u'Test', u'irisSeqId': u'315433', u'attachments': [], u'requestContext': {u'apiArgs': {}}, u'messageMetadata': {u'timestamp': u'1556220634563', u'tags': [u'source:chat:orca', u'app_id:256002347743983'], u'actorFbId': u'100012*********', u'offlineThreadingId': u'6527262425*********', u'messageId': u'mid.$gAAd9PrGssaZwhz-tw1qVfpfaCTLh', u'folderId': {u'systemFolderId': u'INBOX'}, u'threadKey': {u'threadFbId': u'2108033059303846'}}, u'participants': [u'100012*********', u'100022*********', u'100002*********'], u'class': u'NewMessage', u'irisTags': []}}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 1505, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "messengerLogger.py", line 385, in onMessage
    author_nickname = self.fetchThreadInfo(thread_id)[thread_id].nicknames[author_id]
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 712, in fetchThreadInfo
    rtn[_id] = graphql_to_group(entry)
  File "/usr/local/lib/python2.7/dist-packages/fbchat/graphql.py", line 211, in graphql_to_group
    c_info = get_customization_info(group)
  File "/usr/local/lib/python2.7/dist-packages/fbchat/graphql.py", line 43, in get_customization_info
    'color': graphql_color_to_enum(info.get('outgoing_bubble_color'))
  File "/usr/local/lib/python2.7/dist-packages/fbchat/graphql.py", line 34, in graphql_color_to_enum
    raise FBchatException('Could not get ThreadColor from color: {}'.format(color))
FBchatException: Could not get ThreadColor from color: FFF01D6A
```

## Environment information
- Python version 2.7
- `fbchat` version latest from pip at the time of writting

**Comment by madsmtm** [comment]
Hi @TurtleForGaming, thanks for the report!

This is a known issue, and has been fixed in https://github.com/carpedm20/fbchat/pull/371, and released in `v1.5.0`. So, good news, you can run `python -m pip install --upgrade fbchat`, and the issue should resolve itself! 😉 Additionally, you can verify the installed version by typing `python -m pip show fbchat`.

I'll close this for now, but if you're still having trouble, please feel free to reopen!
