### ISSUE TITLE
Cookies Not Loaded from file

### ISSUE THREAD

**Issue by AshwinPathi** [carpedm20/fbchat#450]
## Description of the problem
When reading a cookie json file into a client, I receive a `AttributeError: 'NoneType' object has no attribute 'group'` error. 

## Code to reproduce
```py
	client = None
	client_og = None
	my_file = Path("auth_details.py")
	user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36'
	cookies = {}
	if my_file.is_file():
		import auth_details
		print("Log into client_og")
		client_og = Client(auth_details.FB_EMAIL, auth_details.FB_PASS)
		print(client_og.isLoggedIn())
		cookies = client_og.getSession()
		print(client_og.isLoggedIn())
		cookies2 = {}
		cookie_file=Path('session.json')
		if(cookie_file.is_file() == False):
			print("cookies dont exist already, making them now")
			with open('session.json', 'w') as cf:
				json.dump(cookies, cf)
		with open('session.json', 'r') as cf2:
			cookies2 = json.load(cf2)
		print("Hopefuly you dont need to log into client2, which is the client that uses cookies")
		client = Client(auth_details.FB_EMAIL, auth_details.FB_PASS, user_agent=user_agent, session_cookies=cookies2)

		if client.isLoggedIn():
			print("Logging out of client 1...")
			client.logout()
		print("WAIT 5 SECONDS")
		time.sleep(5)
		if(client_og.isLoggedIn()):
			print("Logging out of client 2...")
			client_og.logout()
		else:
			print("original client is not logged in")
```

## Traceback
```
Log into client_og
Logging in {EMAIL}...
Please enter your 2FA code --> {CORRECT 2FA CODE}
Submitting 2FA code.
Saving browser.
Login of {EMAIL} successful.
True
True
Hopefuly you dont need to log into client2, which is the client that uses cookies
Failed loading session
Traceback (most recent call last):
  File "~/environments/facebookBot/lib/python3.7/site-packages/fbchat/_client.py", line 222, in setSession
    state = State.from_cookies(session_cookies, user_agent=user_agent)
  File "~/environments/facebookBot/lib/python3.7/site-packages/fbchat/_state.py", line 193, in from_cookies
    return cls.from_session(session=session)
  File "~/environments/facebookBot/lib/python3.7/site-packages/fbchat/_state.py", line 175, in from_session
    fb_dtsg = FB_DTSG_REGEX.search(r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Logging in {EMAIL}...
```

## Environment information
- Python 3.7.3
- `fbchat` 1.7.3
- 2-Factor authentication is in use for the particular facebook account I am using.

I understand that there was a previous pos about this issue, but that post is a few months old now. The final solution that was offered works (adding two different client instantiations), but I would like to avoid creating two clients if possible. In the example code I sent, I use this two-client method, and this works, but upon commenting out the first client login, the session file fails to load giving the error I mentioned above.

**Comment by kapi2289** [comment]
I think this might be a problem with the `client.logout()`. Using this destroys the session, so you can't use it anymore. Try to get session and don't use `logout` function and see what happens. :wink:

**Comment by chalermporn17PPA** [comment]
I didn't use client.logout() but it still not load.
this is my code.

```
from fbchat import Client
import json
from fbchat.models import *

cookies = {}
user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36'

try:
    with open('session.json','r') as f:
        cookies = json.load(f)
except:
    pass

if cookies == {} :
    email = input('email : ')
    password = input('password : ')
    client = Client(email,password,user_agent=user_agent)
else :
    print('found cookies')
    client = Client('','',user_agent=user_agent,session_cookies=cookies)
print("Complete")

with open('session.json','w') as f:
    json.dump(client.getSession(),f)
```

### First time log in everything is fine.
```
email : my-email@hotmail.com
password : mypassword
Logging in my-email@hotmail.com...
Please enter your 2FA code --> 8596 8714
Submitting 2FA code.
Complete
Login of my-email@hotmail.com successful.
```
session.json is also has data

### Second time.
```
found cookies
Logging in ...
Traceback (most recent call last):
  File "/home/chalermporn/Desktop/PythonPJ/Pia_BOT/main.py", line 20, in <module>
    client = Client('','',user_agent=user_agent,session_cookies=cookies)
  File "/home/chalermporn/Desktop/PythonPJ/Pia_BOT/python/lib/python3.7/site-packages/fbchat/_client.py", line 104, in __init__
    self.login(email, password, max_tries, user_agent=user_agent)
  File "/home/chalermporn/Desktop/PythonPJ/Pia_BOT/python/lib/python3.7/site-packages/fbchat/_client.py", line 202, in login
    raise FBchatUserError("Email and password not set")
fbchat._exception.FBchatUserError: Email and password not set
```

**Comment by madsmtm** [comment]
I'll close this, and assume that @kapi2289's suggestion fixed this
