### ISSUE TITLE
MQTT message parser error

### ISSUE THREAD

**Issue by lanSs** [carpedm20/fbchat#485]
## Description of the problem
Unable to parse MQTT message.

## Code to reproduce
I'm using the latest `mautrix-faceboot` bridge: `0.1.0.dev14` 

## Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fbchat/_client.py", line 2874, in _try_parse_mqtt
    await self._parse_mqtt(event_type, event_data)
  File "/usr/lib/python3.7/site-packages/fbchat/_client.py", line 2882, in _parse_mqtt
    delta.get("lastIssuedSeqId") or delta.get("irisSeqId") or 0)
TypeError: '>' not supported between instances of 'str' and 'int'
```

## Environment information
Docker envrionment: `dock.mau.dev/tulir/mautrix-facebook:latest`

This is the message which produces the traceback:
```
{
	'deltas': [{
		'attachments': [],
		'body': 'REDACTED',
		'irisSeqId': 'REDACTED',
		'irisTags': ['DeltaNewMessage', 'is_from_iris_fanout'],
		'messageMetadata': {
			'actorFbId': 'REDACTED',
			'folderId': {
				'systemFolderId': 'INBOX'
			},
			'messageId': 'REDACTED',
			'offlineThreadingId': 'REDACTED',
			'skipBumpThread': False,
			'tags': ['source:chat:orca', 'app_id:REDACTED', 'hot_emoji_size:small'],
			'threadKey': {
				'threadFbId': 'REDACTED'
			},
			'threadReadStateEffect': 'MARK_UNREAD',
			'timestamp': '1574614460384'
		},
		'participants': ['REDACTED', 'REDACTED'],
		'requestContext': {
			'apiArgs': {}
		},
		'tqSeqId': '124412',
		'class': 'NewMessage'
	}],
	'firstDeltaSeqId': 305192,
	'lastIssuedSeqId': 305192,
	'queueEntityId': 1521123381
}
```

**Comment by kapi2289** [comment]
This is a problem with [tulir/fbchat-asyncio](https://github.com/tulir/fbchat-asyncio) `fbchat` fork. Actually, we're all having a problem now because Facebook has changed the protocol. See #483 for more info.

**Comment by lanSs** [comment]
Thank you, in this case I will follow #483, and close this one
