### ISSUE TITLE
Attribute Error: module has no attribute Client

### ISSUE THREAD

**Issue by aviaryan** [carpedm20/fbchat#5]
Hello
I am using Python x64 3.4.3 on Windows 8.1. When I try to run the sample code you provided, I face the following error.

```
Traceback (most recent call last):
  File "S:\Dev\python\fbchat.py", line 1, in <module>
    import fbchat
  File "S:\Dev\python\fbchat.py", line 3, in <module>
    client = fbchat.Client("YOUR_ID", "YOUR_PASSWORD")
AttributeError: 'module' object has no attribute 'Client'
```

The interesting thing is that your lib **works perfectly** when I run the same code in the **Python shell**. But when I save the code in a file script.py and call `python script.py`, it gives me the error.

**Comment by aviaryan** [comment]
Never mind, my file was named as fbchat.py so import fbchat imported the file itself.
