### ISSUE TITLE
How to fix this error, whenever i receive a message from someone else it shows this error but when it's my alt account it works fine

### ISSUE THREAD

**Issue by LanzTokisaki** [carpedm20/fbchat#549]
Exception in parsing of {'deltas': [{'attachments': [], 'body': '.say TestMessage', 'irisSeqId': '124', 'irisTags': ['DeltaNewMessage', 'is_from_iris_fanout'], 'messageMetadata': {'actorFbId': '100028238374547', 'folderId': {'systemFolderId': 'INBOX'}, 'messageId': 'mid.$gAAs5iE00J3J3hqnphVxVWSmI6a6V', 'offlineThreadingId': '6653322059435323029', 'skipBumpThread': False, 'tags': ['source:chat:orca', 'app_id:256002347743983'], 'threadKey': {'threadFbId': '3159482317416306'}, 'threadReadStateEffect': 'MARK_UNREAD', 'timestamp': '1586275590533'}, 'participants': ['100034231632684', '100049943764124', '100028238374547'], 'requestContext': {'apiArgs': {}}, 'tqSeqId': '72', 'class': 'NewMessage'}], 'firstDeltaSeqId': 124, 'lastIssuedSeqId': 124, 'queueEntityId': 100049943764124}
Traceback (most recent call last):
  File "C:\Users\tokisaki\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_client.py", line 2820, in _parse_message
    self._parse_payload(topic, data)
  File "C:\Users\tokisaki\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_client.py", line 2758, in _parse_payload
    self._parseDelta(delta)
  File "C:\Users\tokisaki\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_client.py", line 2722, in _parseDelta
    self.onMessage(
  File "C:\Users\tokisaki\Desktop\Facebook Bot Chat\LanzTokisakiBot.py", line 11, in onMessage
    self.markAsRead(author_id)
  File "C:\Users\tokisaki\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_client.py", line 1930, in markAsRead
    self._readStatus(True, thread_ids)
  File "C:\Users\tokisaki\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_client.py", line 1917, in _readStatus
    j = self._payload_post("/ajax/mercury/change_read_status.php", data)
  File "C:\Users\tokisaki\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_client.py", line 116, in _payload_post
    return self._state._payload_post(url, data, files=files)
  File "C:\Users\tokisaki\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_state.py", line 261, in _payload_post
    j = self._post(url, data, files=files)
  File "C:\Users\tokisaki\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_state.py", line 246, in _post
    _util.handle_payload_error(j)
  File "C:\Users\tokisaki\AppData\Local\Programs\Python\Python38\lib\site-packages\fbchat\_util.py", line 143, in handle_payload_error
    raise error_cls(
fbchat._exception.FBchatInvalidParameters: Error #1357031 when sending request: The content you requested cannot be displayed right now. It may be temporarily unavailable, the link you clicked on may have expired, or you may not have permission to view this page.

**Comment by huskyy8y8** [comment]
I want to ask you how to solve it
