### ISSUE TITLE
Unable to login after last facebook update

### ISSUE THREAD

**Issue by mprzenzak** [carpedm20/fbchat#551]
Simply login code doesn't work
```
from fbchat import Client
client = Client("myemail@gmail.com", "mypassword")
```

## Traceback
```
Attempt #1 failed, retrying
Traceback (most recent call last):
  File "C:\...\fbchat\_client.py", line 209, in login
    user_agent=user_agent,
  File "C:\...\fbchat\_state.py", line 149, in login
    return cls.from_session(session=session)
  File "C:\...\fbchat\_state.py", line 186, in from_session
    fb_dtsg = FB_DTSG_REGEX.search(r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

## Environment information
- Python version 3.6
- `fbchat` version 1.9.6

**Comment by BahMike** [comment]
I can still login normally. Maybe this is a regional problem? (fbchat 1.9.6)

**Comment by mprzenzak** [comment]
Hmmm. It might be more complicated. I asked my friend to login using my script and it works. The fact is that I could login two weeks ago when I last used my script and didn't changed anything and now I can't use it. In the meantime I switched to new facebook version in the browser.

**Comment by BahMike** [comment]
Can you try switching back? This might be the reason.

**Comment by mprzenzak** [comment]
Unfortunately I tried without any result.

**Comment by madsmtm** [comment]
Might be related to https://github.com/carpedm20/fbchat/issues/546. I'll have a look at some point
