### ISSUE TITLE
AttributeError: 'str' object has no attribute 'logout'

### ISSUE THREAD

**Issue by orzechszek** [carpedm20/fbchat#626]
## Description of the problem
After successfully sent message I'm getting an error:

Cannot invoke service for `fbchat'
Traceback (most recent call last):
  File "/opt/mqttwarn/lib/python2.7/site-packages/mqttwarn/core.py", line 508, in processor
    notified = timeout(module.plugin, (srv, st))
  File "/opt/mqttwarn/lib/python2.7/site-packages/mqttwarn/util.py", line 133, in timeout
    raise it.exception
AttributeError: 'str' object has no attribute 'logout'

## Environment information
- Python version: 2.7.18rc1
- `fbchat` version - 1.9.7

**Comment by orzechszek** [comment]
Please fix in v1 project - fbchat 1.9.7 available through pip.
