### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by edikiuspro** [carpedm20/fbchat#642]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Voting/Voting.py", line 368, in <module>
    client=Bot("login","password")
  File "/data/data/com.termux/files/home/Voting/fbchat/_client.py", line 103, in __init__
    self.login(email, password, max_tries, user_agent=user_agent)
  File "/data/data/com.termux/files/home/Voting/fbchat/_client.py", line 205, in login
    self._state = State.login(
  File "/data/data/com.termux/files/home/Voting/fbchat/_state.py", line 139, in login
    r = session.post("https://m.facebook.com/login.php?login_attempt=1", data=data)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by edikiuspro** [comment]
Okay i dont know how but with time it just fixed
