### ISSUE TITLE
Can't login with max retries failure

### ISSUE THREAD

**Issue by stefanhdao** [carpedm20/fbchat#65]
Getting this error (I subclassed the Client class and cloned this library into my repo) when trying to login. Anyone else hitting this error?

```
Traceback (most recent call last):
  File "fb_chat.py", line 11, in <module>
    client = fb_client.FbClient(username, password)
  File "/Users/user/Desktop/FBMessengerPython/fb_client.py", line 11, in __init__
    super(FbClient, self).__init__(email, password, debug, user_agent)
  File "/Users/user/Desktop/FBMessengerPython/fbchat/client.py", line 88, in __init__
    if not self.login():
  File "/Users/user/Desktop/FBMessengerPython/fbchat/client.py", line 143, in login
    soup = bs(self._get(MobileURL).text, "lxml")
  File "/Users/user/Desktop/FBMessengerPython/fbchat/client.py", line 124, in _get
    return self._session.get(url, headers=self._header, params=payload, timeout=timeout)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='m.facebook.com', port=443): Max retries exceeded with url: /?seq=0&__req=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1073ae490>: Failed to establish a new connection: [Errno 65] No route to host',))
```

**Comment by thekindlyone** [comment]
Is this still happening? Looks like the js folks issue was solved automatically.

**Comment by stefanhdao** [comment]
It still happens but every now and then I'm able to connect in fine

**Comment by stefanhdao** [comment]
haven't really encountered this problem in multiple places, think it was a networking issue at my location
