### ISSUE TITLE
Can't listen() Error #1357005

### ISSUE THREAD

**Issue by edikiuspro** [carpedm20/fbchat#651]
Code:

client=Bot(login,password)
client.listen()

Error:

Traceback (most recent call last):
  File "C:\Users\Admin\OneDrive\Voting.py", line 578, in <module>
    client2.listen()
  File "C:\Users\Admin\OneDrive\fbchat\_client.py", line 2883, in listen
    self.startListening()
  File "C:\Users\Admin\OneDrive\fbchat\_client.py", line 2831, in startListening
    self._mqtt = Mqtt.connect(
  File "C:\Users\Admin\OneDrive\fbchat\_mqtt.py", line 47, in connect
    sequence_id=cls._fetch_sequence_id(state),
  File "C:\Users\Admin\OneDrive\fbchat\_mqtt.py", line 132, in _fetch_sequence_id
    (j,) = state._graphql_requests(_graphql.from_doc_id("1349387578499440", params))
  File "C:\Users\Admin\OneDrive\fbchat\_state.py", line 280, in _graphql_requests
    return self._post("/api/graphqlbatch/", data, as_graphql=True)
  File "C:\Users\Admin\OneDrive\fbchat\_state.py", line 248, in _post
    return _graphql.response_to_json(content)
  File "C:\Users\Admin\OneDrive\fbchat\_graphql.py", line 52, in response_to_json
    _util.handle_payload_error(x)
  File "C:\Users\Admin\OneDrive\fbchat\_util.py", line 143, in handle_payload_error
    raise error_cls(
fbchat._exception.FBchatFacebookError: Error #1357005 when sending request: Wystąpił problem w zrealizowaniu Twojego żądania. Pracujemy nad jak najszybszym rozwiązaniem. (Translate: There was a problem fulfilling your request. We are working on a solution as soon as possible. )

**Comment by MohamadOday** [comment]
i have the same issue have you fixed it?

**Comment by MohamadOday** [comment]
I just fixed it by just using an old user agent just use this user agent and it should work:
`"Mozilla/5.0 (X11; U; Linux i686; en-GB; rv:1.8.1.2pre) Gecko/20061023 Firefox/2.0.0.1"`
@edikiuspro

**Comment by edikiuspro** [comment]
Code before:

fbchat._util.USER_AGENTS = ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"]

Code after your fix:

fbchat._util.USER_AGENTS = ["Mozilla/5.0 (X11; U; Linux i686; en-GB; rv:1.8.1.2pre) Gecko/20061023 Firefox/2.0.0.1"]

Now i have this error:

Attempt #1 failed, retrying
Traceback (most recent call last):
  File "C:\Users\Admin\OneDrive\fbchat\_client.py", line 205, in login
    self._state = State.login(
  File "C:\Users\Admin\OneDrive\fbchat\_state.py", line 156, in login
    return cls.from_session(session=session)
  File "C:\Users\Admin\OneDrive\fbchat\_state.py", line 195, in from_session
    revision = int(r.text.split('"client_revision":', 1)[1].split(",", 1)[0])
IndexError: list index out of range
@MohamadOday

**Comment by MohamadOday** [comment]
in _state.py file go to line 195 and change it to this:
`revision = 0`

**Comment by edikiuspro** [comment]
Thanks! Now it works 😄
