### ISSUE TITLE
GraphQL error #3252001: Rate limit exceeded / None

### ISSUE THREAD

**Issue by MrRare2** [carpedm20/fbchat#671]
I'm just using my fbchat script and this happened:
```python
>>> import fbchat
>>> session = fbchat.Client(email, password)
Logging in *****@gmail.com...
Login of *****@gmail.com successful.
>>> session.fetchThreadMessages(a_thread_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fbchat/_client.py", line 768, in fetchThreadMessages
    (j,) = self.graphql_requests(_graphql.from_doc_id("1860982147341344", params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fbchat/_client.py", line 130, in graphql_requests
    return tuple(self._state._graphql_requests(*queries))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fbchat/_state.py", line 276, in _graphql_requests
    return self._post("/api/graphqlbatch/", data, as_graphql=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fbchat/_state.py", line 244, in _post
    return _graphql.response_to_json(content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fbchat/_graphql.py", line 54, in response_to_json
    _util.handle_graphql_errors(value)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fbchat/_util.py", line 160, in handle_graphql_errors
    raise FBchatFacebookError(
fbchat._exception.FBchatFacebookError: GraphQL error #3252001: Rate limit exceeded / None
>>> # yeah
```

I'm using the latest version of fbchat (1.9.7)
I hope you can help me fix this :)

Update: I already fixed it by waiting an entire day

**Comment by benedekaibas** [comment]
what version of Python do you use? I am using 3.12, but I have a problem importing all the needed libraries.

**Comment by MrRare2** [comment]
I'm using Python 3.11.6, if you have problems in importing libraries, make sure it's compatible on your system and installed their dependencies.

**Comment by benedekaibas** [comment]
Thank you for the help!
