### ISSUE TITLE
I can't import fbchat

### ISSUE THREAD

**Issue by nixpal** [carpedm20/fbchat#81]
Hello,
I get this error whenever I try to import fbchat without adding any extra lines

30:52.08 > CMKH1 AUTHENTICATE XOAUTH2
  30:52.11 < + 
  30:52.11 write literal size 112
  30:52.29 < + eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
  30:52.29 write literal size 112
  30:52.36 < CMKH1 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)
  30:52.36 NO response: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
Traceback (most recent call last):
  File "./facebook.py", line 2, in <module>
    import fbchat
  File "/Library/Python/2.7/site-packages/fbchat/__init__.py", line 14, in <module>
    from .client import *
  File "/Library/Python/2.7/site-packages/fbchat/client.py", line 14, in <module>
    import requests
  File "/Library/Python/2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Library/Python/2.7/site-packages/requests/packages/__init__.py", line 27, in <module>
    from . import urllib3
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 41, in <module>
    from .request import RequestMethods
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/request.py", line 7, in <module>
    from .filepost import encode_multipart_formdata
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/filepost.py", line 9, in <module>
    from .fields import RequestField
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/fields.py", line 2, in <module>
    import email.utils
  File "/Users/NixPal/email.py", line 19, in <module>
    imap_conn.authenticate('XOAUTH2', lambda x: auth_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 364, in authenticate
    raise self.error(dat[-1])
imaplib.error: [AUTHENTICATIONFAILED] Invalid credentials (Failure)

**Comment by nixpal** [comment]
Sorry I figured it out.. It's working now
