### ISSUE TITLE
client.sendLocalImage not working

### ISSUE THREAD

**Issue by smitgardhariya** [carpedm20/fbchat#85]
Traceback (most recent call last):
  File "C:\Users\Smit\Desktop\test1.py", line 11, in <module>
    client.sendLocalImage(friend.uid,message='opppsssss',image=os.getcwd()+'\\mamu.jpg')
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 317, in sendLocalImage
    image_id = self.uploadImage({'file': (image, open(image), mimetype)})
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 327, in uploadImage
    return json.loads(r._content[9:])['payload']['metadata'][0]['image_id']
IndexError: list index out of range

**Comment by Dainius14** [comment]
Sending images is still not possible. I'm getting error
`'charmap' codec can't decode byte X in position Y: character maps to <undefined>`

**Comment by madsmtm** [comment]
Assuming this is fixed in the current version ;)
